name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/terraform/**'
  workflow_dispatch:
    inputs:
      comment:
        description: "Why are you applying?"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: terraform-ci

    env:
      TF_VAR_image_tag: ${{ github.sha }}
      TF_WORK_DIR: deploy/terraform/stg
      TF_VAR_app_database_url: ${{ secrets.TF_VAR_APP_DATABASE_URL }}
      TF_VAR_app_database_url_sync: ${{ secrets.TF_VAR_APP_DATABASE_URL_SYNC }}
      TF_VAR_worker_database_url: ${{ secrets.TF_VAR_WORKER_DATABASE_URL }}
      TF_VAR_worker_database_url_sync: ${{ secrets.TF_VAR_WORKER_DATABASE_URL_SYNC }}
      TF_VAR_app_google_client_id: ${{ secrets.TF_VAR_APP_GOOGLE_CLIENT_ID }}
      TF_VAR_app_google_client_secret: ${{ secrets.TF_VAR_APP_GOOGLE_CLIENT_SECRET }}
      TF_VAR_app_secret_key_for_session_middleware: ${{ secrets.TF_VAR_APP_SECRET_KEY_FOR_SESSION_MIDDLEWARE }}
      TF_VAR_app_sentry_dsn: ${{ secrets.TF_VAR_APP_SENTRY_DSN }}

    steps:
      - name: Print reason
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          APPLY_REASON: ${{ github.event.inputs.comment }}
        run: |
          echo "Apply reason: $APPLY_REASON"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::771623671665:role/terraform-ci-role
          aws-region: ap-northeast-1

      - name: Terraform Init
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform apply -input=false -auto-approve
